workspace:
  base: /test
  path: d8-poc

services:
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/d8-poc
  mysql:
    image: fpfis/mysql56
#  selenium:
#    image: selenium/standalone-chrome
#  solr:
#    image: fpfis/solr5

pipeline:

  prepare-mysql:
    image: fpfis/mysql56
    commands:
      - sleep 5
      - mysqladmin -h mysql -uroot create database

  prepare-php:
    image: fpfis/php56-dev
    commands:
      - php --version
      - composer install --ansi

  build-dist:
    image: fpfis/php56-dev
    commands:
      - composer install -o --ansi --no-dev
      - tar --exclude=./.git --exclude=./.gitignore --exclude=./.idea -czf ../${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz .
    when:
      event: tag


  github_release:
    image: plugins/github-release
    files:
      - ../${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag

  slack-notify-build:
    image: plugins/slack
    channel: ci
    secrets:
      - source: slack_webhook
        target: webhook
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

  slack-notify-tag:
    image: plugins/slack
    secrets:
      - source: slack_webhook
        target: webhook
    channel: ci
    when:
      event: tag
      status: success
    template: >
      Package {{repo.name}}-{{build.tag}}.tar.gz built and available at
      https://github.com/ec-europa/{{repo.name}}/releases/download/{{build.tag}}/{{repo.name}}-{{build.tag}}.tar.gz