language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update
  - composer install

before_script:
  # Start PhantomJS server.
  - phantomjs --webdriver=4444 > /dev/null &
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path=`which true`" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Create database.
  - mysql -e 'create database drupal'
  - './vendor/bin/robo project:setup-behat -o "behat.tokens._base_url: http://127.0.0.1:8888"'
  - './vendor/bin/robo project:install -o "database.user: travis"'
  # Run Drush web server.
  - ../vendor/bin/drush --debug runserver :8888 > ~/debug.txt 2>&1 &
  - sleep 4s

script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/behat

notifications:
  email: false
